name: ASP.NET Core Deployment

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.x'

      - name: Build and Publish
        run: |
          dotnet build --configuration Release
          dotnet publish --configuration Release --output ./publish

      - name: Transfer files to server
        run: |
          sudo mkdir -p /var/www/apistaging.fideaweb.id/Publish
          scp -r -o "StrictHostKeyChecking=no" -o "UserKnownHostsFile=/dev/null" -i ${{ env.SSH_AUTH_SOCK }} ./publish/* fidea@103.30.194.242:/var/www/apistaging.fideaweb.id/Publish
